# Generated by Django 4.1.7 on 2023-03-25 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_state_profile_state_remove_profile_username_and_more'),
        ('myHome', '0004_remove_product_user_product_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(blank=True, max_length=200, null=True)),
                ('crop_quan', models.IntegerField(blank=True, null=True)),
                ('crop_price', models.IntegerField(blank=True, null=True)),
                ('crop_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
        ),
    ]
