# Generated by Django 4.1.7 on 2023-03-26 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_state_profile_state_remove_profile_username_and_more'),
        ('myHome', '0007_worker_portal_alter_sell_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_to_Farmeasy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_quantity', models.IntegerField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('crop_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_obj', models.CharField(blank=True, max_length=200, null=True)),
                ('cart_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
        ),
    ]
