# Generated by Django 4.1.7 on 2023-04-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myHome', '0014_alter_sell_product_crop_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell_product',
            name='crop_img',
        ),
    ]
