# Generated by Django 4.1.7 on 2023-04-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHome', '0016_sell_product_crop_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_product',
            name='crop_img',
            field=models.ImageField(blank=True, default='wheat.jpg', null=True, upload_to=''),
        ),
    ]
