# Generated by Django 4.1.7 on 2023-04-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHome', '0017_alter_sell_product_crop_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_to_farmeasy',
            name='crop_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
