# Generated by Django 4.1.7 on 2023-04-03 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_state_profile_state_remove_profile_username_and_more'),
        ('myHome', '0019_alter_user_to_farmeasy_crop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_to_farmeasy',
            name='crop_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
