# Generated by Django 4.1.7 on 2023-04-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myHome', '0025_sell_product_selling_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell_product',
            name='selling_qr_code',
        ),
    ]
