# Generated by Django 4.1.7 on 2023-04-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHome', '0026_remove_sell_product_selling_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='worker_in_distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('portal_img', models.ImageField(blank=True, null=True, upload_to='distributors_img')),
            ],
        ),
        migrations.CreateModel(
            name='worker_in_warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('worker_img', models.ImageField(blank=True, null=True, upload_to='workers_img')),
            ],
        ),
        migrations.DeleteModel(
            name='Worker_portal',
        ),
    ]
