# Generated by Django 4.1.7 on 2023-04-24 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_qr_code'),
        ('myHome', '0027_worker_in_distribution_worker_in_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_in_distribution',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
        migrations.AddField(
            model_name='worker_in_warehouse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
