# Generated by Django 4.1.7 on 2023-04-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myHome', '0028_worker_in_distribution_user_worker_in_warehouse_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker_in_distribution',
            old_name='portal_img',
            new_name='porter_img',
        ),
    ]
